project_name: lazytodo
before:
  hooks:
    - go test ./...
builds:
  - id: lazytodo
    main: .
    binary: lazytodo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: lazytodo
    builds:
      - lazytodo
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  use: git
